#!/bin/bash
git submodule update --init --remote --force
rebuild_venv="$1"
rebuild_venv="${rebuild_venv:-0}"
source utility-repo-scripts/setup_python_app.sh \
	--debug \
	--package_manager="poetry" \
	--rebuild_venv="$rebuild_venv" \
	--python_version="3.10" \
	--include_isort \
	--python_formatter="black" \
	--pylint_enabled \
	--flake8_enabled \
	--pytest_enabled \
	--overwrite_vscode_launch \
	--line_length=125
