# pylint: disable=invalid-name
# Generated by Django 4.1.7 on 2023-03-10 05:37

from django.db import migrations

from api.csv_utils import csv_import


def create_restaurants(apps, schema_editor):
    # We can't import the Restaurant model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    restaurant_historical_model = apps.get_model("api", "Restaurant")  # pylint: disable=invalid-name
    restaurants = csv_import("api/migrations/data/restaurants.csv", restaurant_historical_model)
    for restaurant in restaurants:
        restaurant.save()  # type: ignore


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_restaurants)]
